FROM maven:3.9-eclipse-temurin-21-jammy AS builder

RUN mkdir -p /usr/app
WORKDIR /usr/app

COPY pom.xml .
COPY src/ ./src

RUN mvn clean package
RUN ls -lha ./target/liberty/wlp/usr/shared/resources & sleep 10

FROM open-liberty:full

COPY --chown=1001:0 --from=builder /usr/app/src/main/liberty/config/server.xml_pg /config/server.xml
COPY --chown=1001:0 --from=builder /usr/app/src/main/liberty/config/bootstrap.properties /config/bootstrap.properties
COPY --chown=1001:0 --from=builder /usr/app/target/io.openliberty.sample.daytrader8.war /config/apps/
COPY --chown=1001:0 --from=builder /usr/app/target/liberty/wlp/usr/shared/resources/PostgresLibs/ /liberty/usr/shared/resources/PostgresLibs/

ENV contextRoot=daytrader
ENV POSTGRES_HOST=
ENV POSTGRES_PORT=5432
ENV MAX_QUOTES=1000
ENV MAX_USERS=500

ENV XMX=512
ENV XMS=8
ENV XMNX=64
ENV CACHE_LIMIT=32
ENV SCMX=16

#
# for kubernetes change the following, make the OPENJ9_JAVA_OPTIONS
# as a env in the container, the other variables can come from configmap
#
# replace placeholders with values in daytrader-config-jvm
# OPENJ9_JAVA_OPTIONS has higher priority than jvm.options
# OPENJ9_JAVA_OPTIONS is unique to OpenJ9 JVM; for other JVMs
# consider replace OPENJ9_JAVA_OPTIONS with JAVA_OPTS
#
#- name: OPENJ9_JAVA_OPTIONS
#  value: "-XX:+UseContainerSupport -Xgcpolicy:gencon -Xtune:virtualized -Xms$(XMS)m -Xmx$(XMX)m -Xmnx$(XMNX)m -XX:SharedCacheHardLimit=$(CACHE_LIMIT)m -Xscmx$(SCMX)m
#
ENV OPENJ9_JAVA_OPTIONS="-XX:+UseContainerSupport -Xgcpolicy:gencon -Xtune:virtualized -Xms${XMS}m -Xmx${XMX}m -Xmnx${XMNX}m -XX:SharedCacheHardLimit=${CACHE_LIMIT}m -Xscmx${SCMX}m"

ENV HTTP_MAX_KEEP_ALIVE_REQUESTS=100
ENV HTTP_PERSIST_TIMEOUT=30
ENV HTTP_READ_TIMEOUT=60
ENV HTTP_WRITE_TIMEOUT=60
ENV CONMGR1_TIMEOUT=30
ENV CONMGR1_AGED_TIMEOUT=280
ENV CONMGR1_MAX_IDLE_TIMEOUT=270
ENV CONMGR1_REAP_TIME=180
ENV CONMGR1_MAX_POOL_SIZE=10
ENV CONMGR1_MIN_POOL_SIZE=4
ENV CONMGR1_PURGE_POLICY=FailingConnectionOnly
ENV CONMGR1_CONN_PER_THREAD=1
ENV CONMGR3_TIMEOUT=0
ENV CONMGR3_AGED_TIMEOUT=0
ENV CONMGR3_MAX_IDLE_TIMEOUT=1
ENV CONMGR3_REAP_TIME=1
ENV CONMGR3_MAX_POOL_SIZE=10
ENV CONMGR3_MIN_POOL_SIZE=4
ENV CONMGR3_PURGE_POLICY=FailingConnectionOnly
ENV CONMGR3_CONN_PER_THREAD=1
ENV CONMGR4_TIMEOUT=30
ENV CONMGR4_AGED_TIMEOUT=280
ENV CONMGR4_MAX_IDLE_TIMEOUT=270
ENV CONMGR4_REAP_TIME=180
ENV CONMGR4_MAX_POOL_SIZE=10
ENV CONMGR4_MIN_POOL_SIZE=4
ENV CONMGR4_PURGE_POLICY=FailingConnectionOnly
ENV CONMGR4_CONN_PER_THREAD=1
ENV CORE_THREADS=0

# RUN configure.sh
