FROM open-liberty:20.0.0.3-full-java8-openj9

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl iputils-ping less net-tools netcat && \
    rm -rf /var/lib/apt/lists/*

COPY --chown=1001:0 liveness_probe.sh /opt/liveness_probe.sh
COPY --chown=1001:0 readness_probe.sh /opt/readness_probe.sh
RUN chmod a+x /opt/*.sh
#COPY --chown=1001:0 src/main/liberty/config/server-k8s.xml /config/server.xml
COPY --chown=1001:0 src/main/liberty/config/server_db2.xml /config/server.xml
COPY --chown=1001:0 src/main/liberty/config/jvm.options /config/jvm.options
COPY --chown=1001:0 target/io.openliberty.sample.daytrader8.war /config/apps
COPY --chown=1001:0 target/liberty/wlp/usr/shared/resources /opt/ol/wlp/usr/shared/resources
COPY --chown=1001:0 resources/db2jars /opt/ol/wlp/usr/shared/resources/db2jars

ENV MAX_QUOTES=10000 \
    MAX_USERS=15000 \
    DB_ADDRESS=derby \
    DB_PORT=1527

EXPOSE 9080 9443

USER 1001

RUN /opt/ol/wlp/bin/server start &&     \
    /opt/ol/wlp/bin/server stop && \
    rm -rf /output/messaging logs/* $WLP_OUTPUT_DIR/.classCache && chmod -R g+rwx /opt/ol/wlp/output/*

