# Dockerfile to build a jmeter container able to drive acmeair
# Results appear on /output in the container
# Must specify the hostname for the acmeair application (or localhost will be assumed)
FROM smarttuning/jmeter_plain

# Copy the script to be executed and other needed files
COPY jmeter_files/toggle-test.sh $JMETER_HOME/bin/toggle-test.sh
COPY jmeter_files/dynamic_init.sh $JMETER_HOME/bin/init.sh
RUN chmod a+x $JMETER_HOME/bin/init.sh

# Environment variables that we want the user to redefine
ENV JTOPUID=499 \
    JHOST=localhost \
    JPORT=9080 \
    JTHREADS=10 \
    JSTEPTHREADS=200 \
    JRAMP=0 \
    JMAXTHINKTIME=200\
    JSTOCKS=999\
    JDURATION=60 \
    JQUOTES=45 \
    JBUYS=40 \
    JSELLS=40 \
    JWAIT_RESP=1000 \
    TEST_GROUP=browsing-jsf\
    TEST_PLAN=dynamic_daytrader8.jmx \
    JWAIT_RESP=1000

EXPOSE 9270

COPY jmeter_files/. $JMETER_HOME/

ENTRYPOINT ["/bin/bash",  "-c", "init.sh"]


